name: Makefile CI

on:
  push

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Build site
      run: make site

    - name: Upload pages artifact
      run: actions/upload-pages-artifact@v2
    
    - name: Deploy to GitHub pages
      run: actions/deploy-pages