name: Makefile CI

on:
  push

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make

    - name: Build static pages
      run: make serve